host: 192.168.101.4
poolSize: 20
zk:
  server: ${host}:2181
  namespace: server
  lock:
    namespace: lock

mybatis:
  type-aliases-package: com.pengjinfei.incubate.model
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: db/mappers/*.xml
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${host}:3306/test?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: mysql
  redis:
    host: ${host}
pagehelper:
  helperDialect: mysql
  support-methods-arguments: true
mapper:
  not-empty: false
  before: false
  identity: MYSQL
  enum-as-simple-type: true